<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-07-14 22:42
=======
# Generated by Django 4.2.3 on 2023-07-14 22:11
>>>>>>> 2b25fc9dabd31d51cfb7a74113da0fa8a32e9d3a

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=32, null=True)),
                ('userId', models.CharField(max_length=32, null=True)),
                ('userPwd', models.CharField(max_length=32, null=True)),
                ('userRrn1', models.CharField(max_length=6, null=True)),
                ('userRrn2', models.CharField(max_length=1, null=True)),
                ('userLink', models.CharField(max_length=2000, null=True)),
            ],
            options={
                'verbose_name': 'Model_tempUser',
                'verbose_name_plural': 'Model_tempUser',
                'db_table': 'tempUser',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=32, null=True)),
                ('userId', models.CharField(max_length=32, null=True)),
                ('userPwd', models.CharField(max_length=32, null=True)),
                ('userRrn1', models.CharField(max_length=6, null=True)),
                ('userRrn2', models.CharField(max_length=1, null=True)),
                ('userLink', models.CharField(max_length=2000, null=True)),
                ('travel_to', models.CharField(max_length=30, null=True)),
                ('userType1', models.CharField(choices=[('option1', '계획형'), ('option2', '즉흥형')], default='option1', max_length=15, null=True)),
                ('userType2', models.CharField(choices=[('option3', '바쁘게 움직이는 여행'), ('option4', '오직 휴식을 위한 여행')], default='option3', max_length=15, null=True)),
                ('userType3', models.CharField(choices=[('option5', '사진 찍는 거 좋아요'), ('option6', '사진 찍는 거 싫어요')], default='option5', max_length=15, null=True)),
                ('userType4', models.CharField(choices=[('option7', '번화가'), ('option8', '자연, 시골')], default='option7', max_length=15, null=True)),
                ('image', models.ImageField(default='images/default_image.png', null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Model_user',
                'verbose_name_plural': 'Model_user',
                'db_table': 'user',
            },
        ),
    ]
