# Generated by Django 4.2.3 on 2023-07-11 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userRrn',
        ),
    ]
