# Generated by Django 4.2.3 on 2023-07-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_userrrn'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userRrn1',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='userRrn2',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
