# Generated by Django 4.2.3 on 2023-07-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_userrrn1_user_userrrn2'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=32)),
                ('userId', models.CharField(max_length=32, unique=True)),
                ('userPwd', models.CharField(max_length=32)),
                ('userRrn1', models.CharField(max_length=6, null=True)),
                ('userRrn2', models.CharField(max_length=1, null=True)),
                ('userLink', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Model_tempUser',
                'verbose_name_plural': 'Model_tempUser',
                'db_table': 'tempUser',
            },
        ),
    ]
