# Generated by Django 4.2.3 on 2023-07-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_tempuser2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='userId',
            field=models.CharField(max_length=32),
        ),
    ]
