# Generated by Django 4.2.3 on 2023-07-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_tempuser_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.CharField(max_length=32),
        ),
    ]
