# Generated by Django 4.2.3 on 2023-07-11 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempUser2',
        ),
    ]
