# Generated by Django 4.2.3 on 2023-07-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_delete_tempuser2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/default_image.png', null=True, upload_to='images/'),
        ),
    ]
