# Generated by Django 4.2.3 on 2023-07-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='travel_to',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
