# Generated by Django 4.2.3 on 2023-07-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_tempuser_userid_alter_tempuser_userlink_and_more'),
        ('account', '0011_user_travel_to'),
    ]

    operations = [
    ]
