<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-07-14 22:42
=======
# Generated by Django 4.2.3 on 2023-07-14 22:11
>>>>>>> 2b25fc9dabd31d51cfb7a74113da0fa8a32e9d3a

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=10, verbose_name='이름')),
            ],
        ),
    ]
