# Generated by Django 4.2.3 on 2023-07-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=10, verbose_name='이름')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
