# Generated by Django 4.2.1 on 2023-07-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MatchUser',
        ),
    ]
