# Generated by Django 4.2.1 on 2023-07-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_rename_user_matchuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchuser',
            name='userName',
            field=models.CharField(max_length=10, null=True, verbose_name='이름'),
        ),
    ]
