# Generated by Django 4.2.3 on 2023-07-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='place',
        ),
        migrations.AddField(
            model_name='post',
            name='travel_to',
            field=models.CharField(max_length=30, null=True, verbose_name='여행지'),
        ),
    ]
